[programs.localnet]
solana_nextjs_counter = "7G18d74wQeXvHVmapcwgfn1vZ3PdgTK8XFhcCKZcUKPk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/mlim/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
