[programs.localnet]
solana_nextjs_counter = "2amnYyb9jAe933VEBSE7YDGZRQgFpYJCeep57oSNSCNt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/mlim/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
